version: "3.9"
services:
  dynamodb:
    image: "amazon/dynamodb-local:1.20.0"
    ports:
      - "58000:8000"
    # volumes:
    #   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql    
    networks:
      - docker-compose-dynamodb
networks:
  docker-compose-dynamodb: