version: "3.9"
services:
  plantuml-server-jetty:
    image: "plantuml/plantuml-server:jetty"
    ports:
      - "58080:8080"
    networks:
      - docker-plantuml-network
networks:
  docker-plantuml-network: