version: "3.9"
services:
  postgres:
    image: "postgres:15.1-alpine3.16"
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'
    # volumes:
    #   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql    
    networks:
      - docker-postgres-network
networks:
  docker-postgres-network: